/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BucketsRouteRouteImport } from './routes/buckets.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BucketsIndexRouteImport } from './routes/buckets.index'
import { Route as BucketsBucketIdRouteImport } from './routes/buckets.$bucketId'

const BucketsRouteRoute = BucketsRouteRouteImport.update({
  id: '/buckets',
  path: '/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIndexRoute = BucketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BucketsRouteRoute,
} as any)
const BucketsBucketIdRoute = BucketsBucketIdRouteImport.update({
  id: '/$bucketId',
  path: '/$bucketId',
  getParentRoute: () => BucketsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buckets': typeof BucketsRouteRouteWithChildren
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/buckets/': typeof BucketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/buckets': typeof BucketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buckets': typeof BucketsRouteRouteWithChildren
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/buckets/': typeof BucketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/buckets' | '/buckets/$bucketId' | '/buckets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/buckets/$bucketId' | '/buckets'
  id: '__root__' | '/' | '/buckets' | '/buckets/$bucketId' | '/buckets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BucketsRouteRoute: typeof BucketsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/buckets': {
      id: '/buckets'
      path: '/buckets'
      fullPath: '/buckets'
      preLoaderRoute: typeof BucketsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/': {
      id: '/buckets/'
      path: '/'
      fullPath: '/buckets/'
      preLoaderRoute: typeof BucketsIndexRouteImport
      parentRoute: typeof BucketsRouteRoute
    }
    '/buckets/$bucketId': {
      id: '/buckets/$bucketId'
      path: '/$bucketId'
      fullPath: '/buckets/$bucketId'
      preLoaderRoute: typeof BucketsBucketIdRouteImport
      parentRoute: typeof BucketsRouteRoute
    }
  }
}

interface BucketsRouteRouteChildren {
  BucketsBucketIdRoute: typeof BucketsBucketIdRoute
  BucketsIndexRoute: typeof BucketsIndexRoute
}

const BucketsRouteRouteChildren: BucketsRouteRouteChildren = {
  BucketsBucketIdRoute: BucketsBucketIdRoute,
  BucketsIndexRoute: BucketsIndexRoute,
}

const BucketsRouteRouteWithChildren = BucketsRouteRoute._addFileChildren(
  BucketsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BucketsRouteRoute: BucketsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
